### ISSUE TITLE
h2db数据库自动创建时出现错误

### ISSUE THREAD

**Issue by zhaodice** [sunyue1380/QuickDAO4#1]
```
var dataSource = new JdbcDataSource();
        dataSource.setUrl("jdbc:h2:C:\\test.db");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        var dao = QuickDAO.newInstance()
                .dataSource(dataSource)
                .entity(Group.class)
                .lazyLoad(true)
                .idStrategy(IdStrategy.AutoIncrement)
                .build();
        var g = new Group();
        g.groupId = 123;
        g.groupName="445555啊test";
        g.id=111;
        dao.insert(g);
```
错误信息：
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "TYPE_NAME" not found; SQL statement:
select table_name, column_name, type_name, character_maximum_length, is_nullable, column_default from information_schema.`columns` where table_schema = 'PUBLIC'; [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "TYPE_NAME" not found; SQL statement:

	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170)
	at org.h2.command.query.Query.prepare(Query.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at cn.schoolwow.quickdao.domain.ConnectionExecutor.newConnectionExecutorItem(ConnectionExecutor.java:42)
	at cn.schoolwow.quickdao.domain.ConnectionExecutor.executeQuery(ConnectionExecutor.java:60)
	at cn.schoolwow.quickdao.builder.ddl.H2DDLBuilder.getEntityPropertyList(H2DDLBuilder.java:112)
	at cn.schoolwow.quickdao.builder.ddl.AbstractDDLBuilder.getDatabaseEntity(AbstractDDLBuilder.java:40)
	at cn.schoolwow.quickdao.dao.sql.ddl.AbstractDDLDAO.refreshDbEntityList(AbstractDDLDAO.java:294)
	... 10 more
```
依赖信息：
```
    implementation 'com.h2database:h2:2.1.214'
    implementation "cn.schoolwow:QuickDAO:4.1.10"
```

**Comment by sunyue1380** [comment]
经测试确实存在问题。请先使用implementation 'com.h2database:h2:1.4.200'版本，此版本经测试不会有问题。
2.1.214的ddl操作目前存在问题，需要等时间修复，感谢反馈哈。

**Comment by zhaodice** [comment]
> implementation 'com.h2database:h2:1.4.200'

好像换到这个版本了还是有这个错误
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "TYPE_NAME" not found; SQL statement:

依赖是
```
    implementation 'com.h2database:h2:1.4.200'
    implementation "cn.schoolwow:QuickDAO:4.1.10"
```

(已经把库删掉重新测试了)

**Comment by sunyue1380** [comment]
这边1.4.200版本本地测试确实没有问题哈。
我的测试代码：
```
package cn.schoolwow.quickdao;

import cn.schoolwow.quickdao.annotation.IdStrategy;
import cn.schoolwow.quickdao.dao.DAO;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.Test;

public class QuickDAOTest {

    @Test
    public void newInstance() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setUrl("jdbc:h2:D:\\test.db");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        DAO dao = QuickDAO.newInstance()
                .dataSource(dataSource)
                .entity(Group.class)
                .lazyLoad(true)
                .idStrategy(IdStrategy.AutoIncrement)
                .build();
        Group g = new Group();
        g.groupId = 123;
        g.groupName="445555啊test";
        g.id=111;
        dao.insert(g);
    }

    private class Group{
        public long id;
        public long groupId;
        public String groupName;
    }
}
```

引用依赖
```
<dependency>
            <groupId>cn.schoolwow</groupId>
            <artifactId>QuickDAO</artifactId>
            <version>4.1.10</version>
        </dependency>
<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
        </dependency>
```

打印出来的日志
```
2022-07-08 09:36:52,652 INFO  [           main] cn.schoolwow.quickdao.QuickDAO:77 [数据源]类型:h2,地址:jdbc:h2:D:\test.db 
2022-07-08 09:36:52,702 DEBUG [           main] c.s.q.handler.DefaultEntityHandler:439 [跳过常量或静态变量]this$0,该属性被static或者final修饰! 
2022-07-08 09:36:52,719 INFO  [           main] cn.schoolwow.quickdao.QuickDAO:307 [开启懒加载功能] 
2022-07-08 09:36:52,719 INFO  [           main] c.s.quickdao.dao.DAOInvocationHandler:36 [QuickDAO懒加载初始化] 
2022-07-08 09:36:52,764 DEBUG [           main] c.s.quickdao.domain.ConnectionExecutor:183 [生成新表]耗时:3ms,影响行数:0,执行SQL:create table `GROUP`(`ID` BIGINT,`GROUP_ID` BIGINT,`GROUP_NAME` VARCHAR(255)); 
2022-07-08 09:36:52,777 DEBUG [           main] c.s.quickdao.domain.ConnectionExecutor:183 [插入对象]耗时:1ms,影响行数:1,执行SQL:insert into `GROUP`(`ID`,`GROUP_ID`,`GROUP_NAME`) values(111,123,'445555啊test')
```

**Comment by zhaodice** [comment]
确实，那我再等等XD

**Comment by sunyue1380** [comment]
不知道你是否一定需要使用h2 的2.1.214版本，如果需求不是很强烈的话，我建议使用1.4.200即可。
我看了一下，h2的1.x版本和2.x版本差异比较大，QuickDAO要同时支持两个版本的话，改动起来比较麻烦，也比较耗费时间。所以我先暂时关闭这个issue，如果你确实有很强烈的需求，可以再跟我沟通。
